### Get Item List
GET http://localhost:5083/items

### Get Item
GET http://localhost:5083/items/1

### Create Item
POST http://localhost:5083/items
Content-Type: application/json

{
    "name": "Item 1",
    "price": 9.99
}

### Update Item
PUT http://localhost:5083/items/1
Content-Type: application/json

{
    "name": "Pizza",
    "price": 9.99
}

### Delete Item
DELETE http://localhost:5083/items/1